<Project>
  <PropertyGroup>
    <Authors>m1sh3r</Authors>
    <Copyright>m1sh3r // $([System.DateTime]::UtcNow.ToString("yyyy"))</Copyright>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
